# ----
#                    ▓▓░  ▓▓▓  ░▓▓▓
#   -. .-.   .-. .- ▓░ ▓░▓░   ░▓  ░▓ -. .-.   .-. .-
#   ||\|||\ /|||\|| ▓▓▓▓░▓░░▓▓░▓     ||\|||\ /|||\||
#   |/ \|||\|||/ \| ▓░ ▓░▓░ ░▓░▓  ░▓ |/ \|||\|||/ \|
#   ¯   `-¯ `-'   ` ▓░ ▓░ ▓▓▓  ░▓▓▓  ¯   `-¯ `-'   `
#  T H E  A P P L I E D  G E N O M I C S  C E N T R E
#           --- Coding a better harvest ---
# Background ----
# This short script is an add on to the function "function_iteratively-pull-significant-CpG-sites.R"
# and thereby also works with the function "function_filtered-CpG-sites-by-analysis-of-variance-tests.R"
# The purpose of this script is to generate significance markers for the adjusted *p*-values generated by the other two functions
add_significance_markers <- function(input_df) {
  sig_w_padj_and_markers <- input_df[0,] %>%
    mutate(significance_maker = NA)
  if (input_df$p_adjusted <= 0.05 & input_df$p_adjusted > 0.01) {
    significance_marker = "*"
  } else if (input_df$p_adjusted <= 0.01 & input_df$p_adjusted > 0.001) {
    significance_marker = "**"
  } else if (input_df$p_adjusted <= 0.001 & input_df$p_adjusted > 0.0001) {
    significance_marker = "***"
  } else if (input_df$p_adjusted <= 0.0001) {
    significance_marker = "****"
  } else {
    significance_marker = "NS"
  }
  sig_w_padj_and_markers <<- sig_w_padj_and_markers
}